"""Provenance for the three family-definition files vendored under auric_gwas/data/.

Those files are byte-for-byte copies of frozen artifacts produced by the staph_snp_db
(SauSNP) build. They froze at Stage 4 of that build and are stable across annotation-layer
db_version bumps (0.6.0 -> 0.6.3 did not touch them); they change only on a panel/coordinate
re-freeze. Because they are copied by hand, this module records where each came from and its
sha256 in data/PROVENANCE.json so drift is verifiable instead of silent:

  * scripts/sync_from_staph_snp_db.py re-copies the files and rewrites the manifest;
  * auric_gwas/tests/test_data_sync.py fails if a vendored file no longer matches the manifest,
    and (when the staph_snp_db checkout is present) if the live source no longer matches either.

Standard library only; no side effects on import.
"""
from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent / "data"
MANIFEST = DATA_DIR / "PROVENANCE.json"

SOURCE_REPO = "haslamdb/staph_snp_db"

# vendored basename (under data/) -> path relative to the staph_snp_db repo root
VENDORED_FILES: dict[str, str] = {
    "stage4_core_cds.tsv": "results/qc/stage4_core_cds.tsv",
    "stage4_core_igr.tsv": "results/qc/stage4_core_igr.tsv",
    "excluded_features.txt": "config/excluded_features.txt",
}


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def staph_snp_db_root() -> Path | None:
    """Resolve the staph_snp_db checkout: $STAPH_SNP_DB, else the sibling ../staph_snp_db.

    Returns None if neither exists — the manifest self-check still runs without it.
    """
    env = os.environ.get("STAPH_SNP_DB")
    candidates = [Path(env)] if env else []
    candidates.append(Path(__file__).resolve().parents[2] / "staph_snp_db")
    for c in candidates:
        if (c / "db_version.json").is_file():
            return c
    return None


def build_manifest(root: Path) -> dict:
    """Read the current staph_snp_db freeze and hash each source file into a manifest dict."""
    dbv = json.loads((root / "db_version.json").read_text())
    files = {}
    for name, rel in VENDORED_FILES.items():
        src = root / rel
        files[name] = {"source": rel, "sha256": sha256_file(src)}
    return {
        "_comment": "Auto-generated by scripts/sync_from_staph_snp_db.py. Do not hand-edit; "
                    "re-run the sync script after a staph_snp_db panel/coordinate re-freeze.",
        "source_repo": SOURCE_REPO,
        "db_version": dbv.get("db_version", "unknown"),
        "backbone_panel_sha256": dbv.get("backbone_panel", {}).get("sha256"),
        "coordinate_profile_set_sha256":
            dbv.get("coordinate_system", {}).get("profile_hmm_checksums", {}).get("profile_set_sha256"),
        "files": files,
    }


def load_manifest() -> dict:
    return json.loads(MANIFEST.read_text())


def verify_against_manifest() -> list[str]:
    """Re-hash each vendored file against data/PROVENANCE.json. Returns a list of problem strings.

    Self-contained: needs no staph_snp_db checkout. Empty list means the vendored copies match
    the recorded manifest.
    """
    problems: list[str] = []
    if not MANIFEST.is_file():
        return [f"manifest missing: {MANIFEST}"]
    manifest = load_manifest()
    recorded = manifest.get("files", {})
    for name in VENDORED_FILES:
        local = DATA_DIR / name
        if name not in recorded:
            problems.append(f"{name}: not listed in manifest")
            continue
        if not local.is_file():
            problems.append(f"{name}: vendored file missing at {local}")
            continue
        got = sha256_file(local)
        want = recorded[name].get("sha256")
        if got != want:
            problems.append(f"{name}: vendored sha256 {got} != manifest {want}")
    extra = set(recorded) - set(VENDORED_FILES)
    if extra:
        problems.append(f"manifest lists unknown files: {sorted(extra)}")
    return problems


def verify_against_source(root: Path) -> list[str]:
    """Compare the manifest's recorded sha256 to the live staph_snp_db source files.

    Non-empty means the upstream freeze changed since the last sync — re-run the sync script.
    """
    problems: list[str] = []
    manifest = load_manifest()
    recorded = manifest.get("files", {})
    for name, rel in VENDORED_FILES.items():
        src = root / rel
        if not src.is_file():
            problems.append(f"{name}: source missing at {src}")
            continue
        got = sha256_file(src)
        want = recorded.get(name, {}).get("sha256")
        if got != want:
            problems.append(f"{name}: source sha256 {got} != manifest {want} (upstream re-froze)")
    # db_version is recorded for provenance only; annotation-layer bumps advance it without touching
    # these Stage-4 files, so a version mismatch alone is not a content-drift failure.
    return problems


def live_db_version(root: Path) -> str | None:
    return json.loads((root / "db_version.json").read_text()).get("db_version")
