"""Project user assemblies onto the frozen AURIC coordinate system — read-only against the panel.

Reuses the validated cohort-genotyping fork (the vendored AURIC genotyping stages 11,12,13,14,17) by
generating a request-scoped `common_paths` and running each stage through _run_stage.py, exactly as
the AD-cohort reuse mechanism does. No line of the validated walk is copied. The
output is a cohort `genotypes.zarr` in the FROZEN 1,231,021-column order that
`scan --source cohort --matrix <out>/genotype_matrix` consumes.

Stage 15 (per-feature noncoding tallies) and 16 (typing) are not run: stage 17 re-aligns the buckets
itself and applies its own gates, so it depends only on stages 11/12 (CDS buckets) and 13/14 (noncoding
buckets). Stage 12 additionally runs call_family (redundant with 17's walk) — a P2 optimisation.
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

from . import paths

STAGES_DIR = Path(__file__).resolve().parent / "stages"
STAGES_CP = STAGES_DIR / "common_paths.py"
PKG_PARENT = Path(__file__).resolve().parents[1]  # dir containing the auric_gwas package
STAGES = {  # numeric prefix -> (script, argv builder)
    "11": ("11_genotype_predict.py", lambda cp, w: ["--input", str(cp / "input_list.tsv"), "--workers", str(w)]),
    "12": ("12_genotype_call.py", lambda cp, w: ["--input", str(cp / "input_list.tsv"), "--workers", str(w)]),
    "13": ("13_extract_igr_alleles.py", lambda cp, w: ["--genome-list", str(cp / "input_list.tsv"), "--workers", str(w)]),
    "14": ("14_extract_ncrna_alleles.py", lambda cp, w: ["--genome-list", str(cp / "input_list.tsv"), "--workers", str(w)]),
    "17": ("17_build_cohort_matrix.py", lambda cp, w: ["--phase", "both", "--workers", str(w),
                                                       "--input-list", str(cp / "input_list.tsv")]),
}

_COMMON_PATHS_TEMPLATE = '''\
"""Auto-generated request-scoped common_paths for auric-gwas (do not edit).

Loads the validated CHOP common_paths under a private name and rebinds every WRITE target to the
request root {coh!r}. Read-only panel inputs, gates, binaries and helper functions are inherited
unchanged. Generated by auric_gwas.genotype.
"""
import importlib.util as _ilu
from pathlib import Path

_spec = _ilu.spec_from_file_location("_auric_chop_cp", r"{chop_cp}")
_chop = _ilu.module_from_spec(_spec)
_spec.loader.exec_module(_chop)
# inherit read-only inputs, gates, binaries, and helper functions (cds_profile, core_cds_families,
# excluded_feature_names, hmm_env, PROF_CDS_FALLBACK, ...) — all reference the frozen panel read-only.
globals().update({{k: v for k, v in vars(_chop).items() if not k.startswith("__")}})

# --- rebind every WRITE target to the request root -------------------------------------------------
COH = Path(r"{coh}")
ASSEMBLIES = Path(r"{assemblies}")
INPUT = COH / "input_list.tsv"
PREDICT = COH / "predict"
BUCKETS = COH / "buckets"
CALLS = COH / "calls"
BUCKETS_NC = COH / "buckets_noncoding"
CALLS_NC = COH / "calls_noncoding"
SWITCHED_NC = COH / "switched_noncoding"
MATRIX = COH / "genotype_matrix"
QC = COH / "qc"
LOGS = COH / "logs"
CDS_DB_UNMASKED = COH / "hmm" / "cds_unmasked050.hmm"
MANIFEST = COH / "__no_manifest__.tsv"   # absent -> stage 17 skips the cohort-metadata merge
RESULTS = COH
COHORT_LABEL = "user_cohort"
SOURCE_LABEL = "user"


def ensure_dirs():
    for d in (PREDICT, BUCKETS, CALLS, BUCKETS_NC, CALLS_NC, SWITCHED_NC, MATRIX, QC, LOGS,
              CDS_DB_UNMASKED.parent):
        d.mkdir(parents=True, exist_ok=True)
'''


def _discover_assemblies(assemblies_dir: Path) -> list[tuple[str, Path]]:
    out = []
    for ext in ("*.fna", "*.fasta", "*.fa"):
        for p in sorted(assemblies_dir.glob(ext)):
            out.append((p.stem, p.resolve()))
    return out


def _read_manifest(manifest: Path) -> list[tuple[str, Path]]:
    import csv
    rows = []
    with open(manifest, newline="") as fh:
        rdr = csv.DictReader(fh, delimiter="\t")
        idc = "genome_id" if "genome_id" in rdr.fieldnames else rdr.fieldnames[0]
        pc = "path" if "path" in rdr.fieldnames else ("assembly_path" if "assembly_path" in rdr.fieldnames else None)
        if pc is None:
            raise SystemExit("manifest needs a 'path' or 'assembly_path' column")
        for r in rdr:
            gid, path = r[idc].strip(), r[pc].strip()
            if gid and path:
                rows.append((gid, Path(path).resolve()))
    return rows


def run_genotype(out: str | Path, *, assemblies_dir: str | Path | None = None,
                 manifest: str | Path | None = None, workers: int = 16,
                 python: str | None = None) -> Path:
    """Genotype the assemblies into <out>/genotype_matrix/genotypes.zarr. Returns the matrix dir."""
    python = python or sys.executable
    paths.assert_bundle_compatible()
    root = paths.assert_not_panel(out)
    root.mkdir(parents=True, exist_ok=True)

    if manifest:
        items = _read_manifest(Path(manifest))
        adir = Path(items[0][1]).parent if items else root
    elif assemblies_dir:
        adir = Path(assemblies_dir).resolve()
        items = _discover_assemblies(adir)
    else:
        raise SystemExit("provide --assemblies <dir> or --manifest <tsv>")
    if not items:
        raise SystemExit("no assemblies found")
    missing = [str(p) for _, p in items if not Path(p).exists()]
    if missing:
        raise SystemExit(f"{len(missing)} assembly files not found (e.g. {missing[:2]})")

    # generate the request-scoped common_paths and the input list
    cp_file = root / "common_paths.py"
    cp_file.write_text(_COMMON_PATHS_TEMPLATE.format(coh=str(root), assemblies=str(adir), chop_cp=str(STAGES_CP)))
    (root / "input_list.tsv").write_text(
        "genome_id\tsource\tcohort\tpath\n"
        + "".join(f"{g}\tuser\tuser_cohort\t{p}\n" for g, p in items))
    print(f"[auric-gwas] genotyping {len(items)} assemblies -> {root}", flush=True)

    for stage in ("11", "12", "13", "14", "17"):
        script, argv = STAGES[stage]
        cmd = [python, "-m", "auric_gwas._run_stage", str(cp_file), str(STAGES_DIR / script),
               *argv(root, workers)]
        print(f"[auric-gwas] === stage {stage} ({script}) ===", flush=True)
        r = subprocess.run(cmd, cwd=str(root),
                           env={**_child_env(), "PYTHONPATH": str(PKG_PARENT)})
        if r.returncode != 0:
            raise SystemExit(f"stage {stage} failed (exit {r.returncode}); nothing merged into the panel")

    _fix_zarr_attrs(root / "genotype_matrix")
    print(f"[auric-gwas] done. matrix at {root / 'genotype_matrix'}. "
          "Nothing under /fastpool/sausnp/db was written.", flush=True)
    return root / "genotype_matrix"


def _child_env() -> dict:
    import os
    return {**os.environ, "OMP_NUM_THREADS": "4", "OPENBLAS_NUM_THREADS": "4", "MKL_NUM_THREADS": "4"}


def _fix_zarr_attrs(matrix_dir: Path) -> None:
    """Overwrite the CHOP-specific 'cohort' zarr attribute on the cohort matrix (write is under the
    request root, never the panel). Purely cosmetic metadata."""
    z = matrix_dir / "genotypes.zarr"
    if not z.exists():
        return
    try:
        import zarr
        g = zarr.open_group(str(z), mode="r+")["genotypes"]
        g.attrs["cohort"] = "user cohort projected onto AURIC via auric-gwas genotype"
    except Exception as e:  # metadata only; never fail the run over this
        print(f"[auric-gwas] note: could not update zarr cohort attr ({e})", file=sys.stderr)
